### ISSUE TITLE
(MAY HAVE) issue in hashmatch

### ISSUE THREAD

**Issue by Roadsong** [momalab/ICSREF#3]
Hi   @tkeliris,
When I was trying to reproduce things you did in your [demo video]( https://asciinema.org/a/9l96XWgNttz1WTdXGIngMAAKe),  I find a problem in hashmatch stage:
```
Environment: Clean Ubuntu 16.04 and 18.04
```
```
reversing@icsref:$ analyze samples/PRG_binaries/In-house/TE.PRG
Working on samples/PRG_binaries/In-house/TE.PRG.
DONE: Hexdump generation
DONE: Header analysis
DONE: String analysis
DONE: I/O analysis
DONE: Find function boundaries
DONE: Function disassembly
DONE: Find dynamic calls
DONE: Find static calls
DONE: Call offsets renaming
Analysis of TE finished.
Total analysis time: 25.6079239845

reversing@icsref:$ !ls results/TE
TE_init_analysis.dat

reversing@icsref:$ hashmatch
Hashmatch module (MAY HAVE) found function maybe_DERIVATIVE_INIT at 0x1150
Hashmatch module (MAY HAVE) found function maybe_INTEGRAL_INIT at 0x15d4

reversing@icsref:$ pidargs
No PID_FIXCYCLE functions identified. Cannot extract arguments.

reversing@icsref:$ graphbuilder
Cleanup complete
Generated graph_TE.svg
```
Even I could build the CFG, the CFG itself was not 100% identical with the picture listed on the paper.

https://ibb.co/TcznjcT

I was not sure how this happened, since everything is okay in your demo video. 

Any help will be appreciated!

**Comment by tkeliris** [comment]
Hello @Roadsong, thank you for catching that. Indeed there was an issue in calculating the hash of functions that is now fixed. Try pulling the latest version and everything should be as in the demo video now.
